node('dind-node') {
  withMaven(maven:'M3') {
    stage('Checkout') {
      git url: 'https://github.com/rafurb/sample-spring-microservices-new.git', credentialsId: 'rafurb', branch: 'master'
    }
    stage('Build') {
      dir('config-service') {
        sh 'mvn clean install'
        def pom = readMavenPom file:'pom.xml'
        print pom.version
        env.version = pom.version
        currentBuild.description = "Release: ${env.version}"
      }
    }
    stage('Image') {
      dir ('config-service') {
        docker.withRegistry('https://localhost:5000') {
          def app = docker.build "rafurb/config-service:${env.version}"
          app.push()
        }
      }
    }
  }
}